services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nom_base_de_donnees
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app_java:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_java
    depends_on:
      - mysql
    ports:
      - "8080:8080"
volumes:
  mysql_data: